### ISSUE TITLE
ESS build in window in Timmi is not showing up

### ISSUE THREAD

**Issue by the-sheen** [draganignjic/timmi-ess-fusion#23]
After pressing on the "ESS" button in Timmi on the bottom right, the pop-up window appears to sign in and then to enter the PIN and usually after that the ESS loaded in the pop-up window and finally the build in ESS window in Timmi appeared. Now the build-in window is not showing up and the ESS in the pop-up window remains where the hours are not in sync with Timmi.

![image](https://github.com/user-attachments/assets/2ac4449a-990d-4181-9ef1-09057c676e1e)

**Comment by draganignjic** [comment]
Hey.

Yes there is a login issue since this week. You can try to update the script by clicking on the "Help" button. If you still have the issue you can contact me in MS Teams.

Regards,
Dragan Ignjic

**Comment by draganignjic** [comment]
This issue was fixed.
