### ISSUE TITLE
sub elements can't be selected

### ISSUE THREAD

**Issue by piif** [draganignjic/timmi-ess-fusion#8]
In task selection, there are some entries like "Attendances & Absences w/o WBS element" which contains "sub elements".
With this script, they disappear during loading, thus we can't select them to add to ess list or to bookmarks

**Comment by txigd** [comment]
Hi piff

Unfortunatelly I don't have any sub elements in my list. Could you please export your worklist html so I can look for a solution?
In Firefox: Right click -> this frame -> Frame Source 
In Chrome: Right click -> view frame source

Please post it here or send it to me by mail (dragan ignjic in the company phone book). 

Regards,
Dragan

**Comment by piif** [comment]
I just tried from Chrome, but without the script, and the result is the same, thus it's not a side effect of your script, but something which works with IE but not with Chrome.
In fact, sub elements are explicitly set to "display: none" just after loading (we can see them during loading, and they disappear just after).

I'll send you an email with html details in a few minutes.

Thanks again for your great job ;-)
